/**
 * Export ledger to CSV (Excel-compatible) or PDF.
 * Uses expo-file-system + expo-sharing + expo-print.
 */
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';

function csvEscape(v) {
  if (v == null) return '';
  const s = String(v);
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

/**
 * transactions: [{ date, merchant, amount, vat, category, trn, notes }]
 */
export async function exportCSV(transactions, opts = {}) {
  const headers = ['Date', 'Merchant', 'Category', 'Amount (AED)', 'VAT (AED)', 'TRN', 'Notes'];
  const rows = transactions.map(t => [
    t.date || '',
    t.merchant || '',
    t.category || '',
    t.amount ?? '',
    t.vat ?? '',
    t.trn || '',
    t.notes || '',
  ]);
  const body = [headers, ...rows].map(r => r.map(csvEscape).join(',')).join('\n');
  const fname = opts.filename || `filey-ledger-${Date.now()}.csv`;
  const path = `${FileSystem.cacheDirectory}${fname}`;
  await FileSystem.writeAsStringAsync(path, body, { encoding: FileSystem.EncodingType.UTF8 });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(path, { mimeType: 'text/csv', dialogTitle: 'Export Ledger CSV' });
  }
  return path;
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, ch => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[ch]);
}

/**
 * Render a polished VAT-ready PDF using Montek theme.
 */
export async function exportPDF(transactions, opts = {}) {
  const totalAmt = transactions.reduce((s, t) => s + (parseFloat(t.amount) || 0), 0);
  const totalVat = transactions.reduce((s, t) => s + (parseFloat(t.vat) || 0), 0);
  const period = opts.period || new Date().toISOString().slice(0, 7);
  const company = opts.company || 'My Company';

  const rowsHtml = transactions.map(t => `
    <tr>
      <td>${escapeHtml(t.date)}</td>
      <td>${escapeHtml(t.merchant)}</td>
      <td>${escapeHtml(t.category)}</td>
      <td class="num">${escapeHtml(t.amount)}</td>
      <td class="num">${escapeHtml(t.vat)}</td>
    </tr>
  `).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Helvetica, sans-serif; color: #0B1435; padding: 32px; }
    .hero { background: #3B6BFF; color: #fff; padding: 24px; border-radius: 16px; margin-bottom: 24px; }
    .hero h1 { margin: 0; font-size: 26px; letter-spacing: -0.5px; }
    .hero p { margin: 4px 0 0; opacity: 0.85; font-size: 13px; }
    .stats { display: flex; gap: 14px; margin-bottom: 20px; }
    .stat { flex: 1; background: #F4F6FB; border-radius: 14px; padding: 14px 18px; }
    .stat .k { font-size: 10px; font-weight: 700; letter-spacing: 1.2px; color: #6B7280; }
    .stat .v { font-size: 22px; font-weight: 800; color: #0B1435; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { text-align: left; background: #F4F6FB; padding: 10px 8px; color: #6B7280; font-weight: 700; letter-spacing: 1px; font-size: 10px; }
    td { padding: 10px 8px; border-bottom: 1px solid #E5E7EB; }
    td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
    .footer { margin-top: 28px; font-size: 10px; color: #6B7280; text-align: center; }
  </style></head><body>
    <div class="hero">
      <h1>VAT Ledger — ${escapeHtml(period)}</h1>
      <p>${escapeHtml(company)} · Generated by Filey · ${new Date().toLocaleDateString()}</p>
    </div>
    <div class="stats">
      <div class="stat"><div class="k">TRANSACTIONS</div><div class="v">${transactions.length}</div></div>
      <div class="stat"><div class="k">TOTAL AMOUNT</div><div class="v">${totalAmt.toFixed(2)} AED</div></div>
      <div class="stat"><div class="k">TOTAL VAT 5%</div><div class="v">${totalVat.toFixed(2)} AED</div></div>
    </div>
    <table>
      <thead><tr>
        <th>Date</th><th>Merchant</th><th>Category</th>
        <th class="num">Amount</th><th class="num">VAT</th>
      </tr></thead>
      <tbody>${rowsHtml}</tbody>
    </table>
    <div class="footer">FTA 5-year retention compliant · Encrypted on-device · filey.app</div>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Export Ledger PDF' });
  }
  return uri;
}
