import LegalLayout from '@/components/dashboard/LegalLayout';

export const metadata = {
  title: 'Terms of Service · Filey',
  description: 'Plain-language terms for using Filey.',
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="April 24, 2026">
      <p>
        Plain-language version — the legally binding version mirrors this in more formal text.
        By using Filey you agree to the points below.
      </p>

      <h2>1. What Filey is</h2>
      <p>
        Filey is a personal / small-business finance copilot. We help you track transactions,
        scan receipts, issue invoices and ask AI questions about your own numbers. Filey is
        <strong> not</strong> a bank, not an accountant, and not a licensed financial adviser. For
        anything legally binding (tax filings, compliance), confirm with a qualified professional.
      </p>

      <h2>2. Your account</h2>
      <ul>
        <li>You are responsible for keeping your password and backup passphrase safe.</li>
        <li>If you lose your encrypted backup passphrase, <strong>no one can recover it</strong> — not even us.</li>
        <li>Do not share your account. Use the Agency plan for team access.</li>
      </ul>

      <h2>3. Free plan</h2>
      <p>The Free plan is available indefinitely, subject to reasonable caps (see the pricing page). We may adjust caps — always in your favour or with 30 days&rsquo; notice if tightening.</p>

      <h2>4. Paid plans</h2>
      <ul>
        <li>14-day free trial. No card charged during trial.</li>
        <li>Billed monthly or yearly as selected. Yearly is paid upfront at a discount.</li>
        <li>Cancel any time; access continues until end of paid period.</li>
        <li>We do not offer pro-rated refunds for mid-cycle cancellations of monthly plans.</li>
        <li>Yearly cancellations within 14 days of initial purchase are refunded in full.</li>
      </ul>

      <h2>5. Acceptable use</h2>
      <p>Do not use Filey to:</p>
      <ul>
        <li>Store illegal financial records or launder funds.</li>
        <li>Attempt to reverse-engineer, scrape, or abuse the service.</li>
        <li>Impersonate another business on invoices generated through the platform.</li>
      </ul>

      <h2>6. Your content</h2>
      <p>
        You keep full ownership of everything you put into Filey — your transactions, invoices,
        receipts and AI conversations are yours. We never claim a license over them.
      </p>

      <h2>7. AI outputs</h2>
      <p>
        AI responses are generated by third-party models you choose. They may contain mistakes.
        Verify anything important. Filey is not liable for decisions made from AI outputs.
      </p>

      <h2>8. Warranties & liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, Filey&rsquo;s total
        liability to you for any claim is capped at the amount you paid us in the 12 months
        preceding the claim (AED 0 on the Free plan).
      </p>

      <h2>9. Governing law</h2>
      <p>These terms are governed by the laws of the United Arab Emirates. Any dispute goes to the Dubai International Financial Centre (DIFC) Courts.</p>

      <h2>10. Changes</h2>
      <p>We may update these terms. Material changes are emailed to paid users and posted in-app 30 days before they take effect.</p>

      <h2>11. Contact</h2>
      <p>Questions? <a href="mailto:legal@filey.ae">legal@filey.ae</a></p>
    </LegalLayout>
  );
}
